config/routes.rb
Rails.application.routes.draw do
  resources :trips
  resources :routes
  resources :transfers
  resources :stops

  root 'routes#index'
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :route

  scope :tram, -> { joins(:route).merge(Route.tram) }
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.includes(:route).tram.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:tam_id, :route_id, :service_id, :trip_headsign, :direction_id, :block_id, :wheelchair_accessible, :bikes_allowed)
    end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_with(model: trip, local: true) do |form| %>
  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
        <% trip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tam_id %>
    <%= form.text_field :tam_id %>
  </div>

  <div class="field">
    <%= form.label :route_id %>
    <%= form.text_field :route_id %>
  </div>

  <div class="field">
    <%= form.label :service_id %>
    <%= form.text_field :service_id %>
  </div>

  <div class="field">
    <%= form.label :trip_headsign %>
    <%= form.text_field :trip_headsign %>
  </div>

  <div class="field">
    <%= form.label :direction_id %>
    <%= form.number_field :direction_id %>
  </div>

  <div class="field">
    <%= form.label :block_id %>
    <%= form.text_field :block_id %>
  </div>

  <div class="field">
    <%= form.label :wheelchair_accessible %>
    <%= form.number_field :wheelchair_accessible %>
  </div>

  <div class="field">
    <%= form.label :bikes_allowed %>
    <%= form.number_field :bikes_allowed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trips</h1>

<table>
  <thead>
    <tr>
      <th>Tam</th>
      <th>Route</th>
      <th>Service</th>
      <th>Trip headsign</th>
      <th>Direction</th>
      <th>Block</th>
      <th>Wheelchair accessible</th>
      <th>Bikes allowed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.tam_id %></td>
        <td><%= link_to trip.route, trip.route %></td>
        <td><%= trip.service_id %></td>
        <td><%= trip.trip_headsign %></td>
        <td><%= trip.direction_id %></td>
        <td><%= trip.block_id %></td>
        <td><%= trip.wheelchair_accessible %></td>
        <td><%= trip.bikes_allowed %></td>
        <td><%= link_to 'Show', trip %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tam:</strong>
  <%= @trip.tam_id %>
</p>

<p>
  <strong>Route:</strong>
  <%= @trip.route_id %>
</p>

<p>
  <strong>Service:</strong>
  <%= @trip.service_id %>
</p>

<p>
  <strong>Trip headsign:</strong>
  <%= @trip.trip_headsign %>
</p>

<p>
  <strong>Direction:</strong>
  <%= @trip.direction_id %>
</p>

<p>
  <strong>Block:</strong>
  <%= @trip.block_id %>
</p>

<p>
  <strong>Wheelchair accessible:</strong>
  <%= @trip.wheelchair_accessible %>
</p>

<p>
  <strong>Bikes allowed:</strong>
  <%= @trip.bikes_allowed %>
</p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>