config/routes.rb
Rails.application.routes.draw do
  resources :trips
  resources :routes
  resources :transfers
  resources :stops

  root 'routes#index'
end

app/models/stop.rb
class Stop < ApplicationRecord
  belongs_to :parent_stop, required: false, class_name: Stop.name

  scope :parents, -> { where(parent_stop: nil) }
  scope :children, -> { where.not(parent_stop: nil) }

  def to_s
    name
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  before_action :set_stop, only: [:show, :edit, :update, :destroy]

  # GET /stops
  # GET /stops.json
  def index
    @stops = Stop.parents.all
  end

  # GET /stops/1
  # GET /stops/1.json
  def show
  end

  # GET /stops/new
  def new
    @stop = Stop.new
  end

  # GET /stops/1/edit
  def edit
  end

  # POST /stops
  # POST /stops.json
  def create
    @stop = Stop.new(stop_params)

    respond_to do |format|
      if @stop.save
        format.html { redirect_to @stop, notice: 'Stop was successfully created.' }
        format.json { render :show, status: :created, location: @stop }
      else
        format.html { render :new }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stops/1
  # PATCH/PUT /stops/1.json
  def update
    respond_to do |format|
      if @stop.update(stop_params)
        format.html { redirect_to @stop, notice: 'Stop was successfully updated.' }
        format.json { render :show, status: :ok, location: @stop }
      else
        format.html { render :edit }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stops/1
  # DELETE /stops/1.json
  def destroy
    @stop.destroy
    respond_to do |format|
      format.html { redirect_to stops_url, notice: 'Stop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stop
      @stop = Stop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stop_params
      params.require(:stop).permit(:tam_id, :code, :name, :lat, :long, :location_type, :parent_stop_id)
    end
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/views/stops/_form.html.erb
<%= form_with(model: stop, local: true) do |form| %>
  <% if stop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stop.errors.count, "error") %> prohibited this stop from being saved:</h2>

      <ul>
        <% stop.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tam_id %>
    <%= form.text_field :tam_id %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat %>
  </div>

  <div class="field">
    <%= form.label :long %>
    <%= form.text_field :long %>
  </div>

  <div class="field">
    <%= form.label :location_type %>
    <%= form.number_field :location_type %>
  </div>

  <div class="field">
    <%= form.label :parent_stop_id %>
    <%= form.text_field :parent_stop_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stops/edit.html.erb
<h1>Editing Stop</h1>

<%= render 'form', stop: @stop %>

<%= link_to 'Show', @stop %> |
<%= link_to 'Back', stops_path %>

app/views/stops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stops</h1>

<table>
  <thead>
    <tr>
      <th>Tam</th>
      <th>Code</th>
      <th>Name</th>
      <th>Lat</th>
      <th>Long</th>
      <th>Location type</th>
      <th>Parent stop</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stops.each do |stop| %>
      <tr>
        <td><%= stop.tam_id %></td>
        <td><%= stop.code %></td>
        <td><%= link_to stop, stop %></td>
        <td><%= stop.lat %></td>
        <td><%= stop.long %></td>
        <td><%= stop.location_type %></td>
        <td><%= stop.parent_stop_id %></td>
        <td><%= link_to 'Show', stop %></td>
        <td><%= link_to 'Edit', edit_stop_path(stop) %></td>
        <td><%= link_to 'Destroy', stop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stop', new_stop_path %>

app/views/stops/new.html.erb
<h1>New Stop</h1>

<%= render 'form', stop: @stop %>

<%= link_to 'Back', stops_path %>

app/views/stops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tam:</strong>
  <%= @stop.tam_id %>
</p>

<p>
  <strong>Code:</strong>
  <%= @stop.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @stop.name %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @stop.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @stop.long %>
</p>

<p>
  <strong>Location type:</strong>
  <%= @stop.location_type %>
</p>

<p>
  <strong>Parent stop:</strong>
  <%= @stop.parent_stop_id %>
</p>

<%= link_to 'Edit', edit_stop_path(@stop) %> |
<%= link_to 'Back', stops_path %>