config/routes.rb
Rails.application.routes.draw do
  resources :trips
  resources :routes
  resources :transfers
  resources :stops

  root 'routes#index'
end

app/models/route.rb
class Route < ApplicationRecord
  # https://developers.google.com/transit/gtfs/reference/#routestxt
  # 0: Tram, streetcar, or light rail. Used for any light rail or street-level system within a metropolitan area.
  # 1: Subway or metro. Used for any underground rail system within a metropolitan area.
  # 2: Rail. Used for intercity or long-distance travel.
  # 3: Bus. Used for short- and long-distance bus routes.
  # 4: Ferry. Used for short- and long-distance boat service.
  # 5: Cable car. Used for street-level cable cars where the cable runs beneath the car.
  # 6: Gondola or suspended cable car. Typically used for aerial cable cars where the car is suspended from the cable.
  # 7: Funicular. Used for any rail system that moves on steep inclines with a cable traction system.
  module RouteTypes
    ALL = [
      TRAM = 0,
      SUBWAY = 1,
      RAIL = 2,
      BUS = 3,
      FERRY = 4,
      CABLE_CAR = 5,
      GONDOLA = 6,
      FUNICULAR = 7
    ]
  end

  scope :tram, -> { where(route_type: RouteTypes::TRAM) }

  def route_type_str
    RouteTypes.constants.find { |c| RouteTypes.const_get(c) == route_type }.to_s.titleize
  end

  def useful_name
    "#{route_type_str} #{short_name}"
  end

  def to_s
    useful_name
  end

  def to_param
    "#{id}-#{to_s}".parameterize
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.tram.all
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:tam_id, :short_name, :long_name, :route_type)
    end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_form.html.erb
<%= form_with(model: route, local: true) do |form| %>
  <% if route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
        <% route.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tam_id %>
    <%= form.text_field :tam_id %>
  </div>

  <div class="field">
    <%= form.label :short_name %>
    <%= form.text_field :short_name %>
  </div>

  <div class="field">
    <%= form.label :long_name %>
    <%= form.text_field :long_name %>
  </div>

  <div class="field">
    <%= form.label :route_type %>
    <%= form.number_field :route_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Routes</h1>

<table>
  <thead>
    <tr>
      <th>Tam</th>
      <th>Useful name</th>
      <th>Short name</th>
      <th>Long name</th>
      <th>Route type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.tam_id %></td>
        <td><%= route.useful_name %></td>
        <td><%= route.short_name %></td>
        <td><%= route.long_name %></td>
        <td><%= route.route_type %></td>
        <td><%= link_to 'Show', route %></td>
        <td><%= link_to 'Edit', edit_route_path(route) %></td>
        <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_route_path %>

app/views/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tam:</strong>
  <%= @route.tam_id %>
</p>

<p>
  <strong>Short name:</strong>
  <%= @route.short_name %>
</p>

<p>
  <strong>Long name:</strong>
  <%= @route.long_name %>
</p>

<p>
  <strong>Route type:</strong>
  <%= @route.route_type %>
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>