config/routes.rb
Rails.application.routes.draw do
  resources :trips
  resources :routes
  resources :transfers
  resources :stops

  root 'routes#index'
end

app/models/transfer.rb
# https://developers.google.com/transit/gtfs/reference/#transferstxt
class Transfer < ApplicationRecord
  # 0 or (empty): This is a recommended transfer point between routes.
  # 1: This is a timed transfer point between two routes. The departing vehicle is expected to wait for the arriving one, with sufficient time for a rider to transfer between routes.
  # 2: This transfer requires a minimum amount of time between arrival and departure to ensure a connection. The time required to transfer is specified by min_transfer_time.
  # 3: Transfers aren't possible between routes at this location.
  module TransferTypes
    ALL = [
      RECOMMENDED = 0,
      WAIT = 1,
      REQUIRE_TIME = 2,
      IMPOSSIBLE = 3
    ]
  end


  belongs_to :from_stop, class_name: Stop.name
  belongs_to :to_stop, class_name: Stop.name

  scope :recommended, -> { where(transfer_type: TransferTypes::RECOMMENDED) }
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :set_transfer, only: [:show, :edit, :update, :destroy]

  # GET /transfers
  # GET /transfers.json
  def index
    @transfers = Transfer.includes(:from_stop, :to_stop).recommended.all
  end

  # GET /transfers/1
  # GET /transfers/1.json
  def show
  end

  # GET /transfers/new
  def new
    @transfer = Transfer.new
  end

  # GET /transfers/1/edit
  def edit
  end

  # POST /transfers
  # POST /transfers.json
  def create
    @transfer = Transfer.new(transfer_params)

    respond_to do |format|
      if @transfer.save
        format.html { redirect_to @transfer, notice: 'Transfer was successfully created.' }
        format.json { render :show, status: :created, location: @transfer }
      else
        format.html { render :new }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transfers/1
  # PATCH/PUT /transfers/1.json
  def update
    respond_to do |format|
      if @transfer.update(transfer_params)
        format.html { redirect_to @transfer, notice: 'Transfer was successfully updated.' }
        format.json { render :show, status: :ok, location: @transfer }
      else
        format.html { render :edit }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfers/1
  # DELETE /transfers/1.json
  def destroy
    @transfer.destroy
    respond_to do |format|
      format.html { redirect_to transfers_url, notice: 'Transfer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transfer
      @transfer = Transfer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transfer_params
      params.require(:transfer).permit(:from_stop_id, :to_stop_id, :transfer_type, :min_transfer_time)
    end
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/transfers/_form.html.erb
<%= form_with(model: transfer, local: true) do |form| %>
  <% if transfer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transfer.errors.count, "error") %> prohibited this transfer from being saved:</h2>

      <ul>
        <% transfer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :from_stop_id %>
    <%= form.number_field :from_stop_id %>
  </div>

  <div class="field">
    <%= form.label :to_stop_id %>
    <%= form.number_field :to_stop_id %>
  </div>

  <div class="field">
    <%= form.label :transfer_type %>
    <%= form.text_field :transfer_type %>
  </div>

  <div class="field">
    <%= form.label :min_transfer_time %>
    <%= form.number_field :min_transfer_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transfers/edit.html.erb
<h1>Editing Transfer</h1>

<%= render 'form', transfer: @transfer %>

<%= link_to 'Show', @transfer %> |
<%= link_to 'Back', transfers_path %>

app/views/transfers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transfers</h1>

<table>
  <thead>
    <tr>
      <th>From stop</th>
      <th>To stop</th>
      <th>Transfer type</th>
      <th>Min transfer time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transfers.each do |transfer| %>
      <tr>
        <td><%= link_to transfer.from_stop, transfer.from_stop %></td>
        <td><%= link_to transfer.to_stop, transfer.to_stop %></td>
        <td><%= transfer.transfer_type %></td>
        <td><%= transfer.min_transfer_time %></td>
        <td><%= link_to 'Show', transfer %></td>
        <td><%= link_to 'Edit', edit_transfer_path(transfer) %></td>
        <td><%= link_to 'Destroy', transfer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transfer', new_transfer_path %>

app/views/transfers/new.html.erb
<h1>New Transfer</h1>

<%= render 'form', transfer: @transfer %>

<%= link_to 'Back', transfers_path %>

app/views/transfers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From stop:</strong>
  <%= @transfer.from_stop_id %>
</p>

<p>
  <strong>To stop:</strong>
  <%= @transfer.to_stop_id %>
</p>

<p>
  <strong>Transfer type:</strong>
  <%= @transfer.transfer_type %>
</p>

<p>
  <strong>Min transfer time:</strong>
  <%= @transfer.min_transfer_time %>
</p>

<%= link_to 'Edit', edit_transfer_path(@transfer) %> |
<%= link_to 'Back', transfers_path %>